approvedGitRepositories:
    - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.15.0.cjs

packageExtensions:
    "eslint-plugin-turbo@*":
        peerDependenciesMeta:
            turbo:
                optional: true
