// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "./packages/db/src/prisma/schema.prisma",
    migrations: {
        path: "./packages/db/src/prisma/migrations",
        seed: "tsx ./packages/db/src/seed.ts"
    },
    datasource: {
        url: process.env.DATABASE_URL!
    }
});